#!/usr/bin/env python3
"""
Alerting Pipeline — Webhook Dispatcher
======================================
Reads un-notified alerts from SQLite (where severity <= 2),
sends notifications via Discord webhook or SMTP email,
marks alerts as notified in database.

Usage:
    python alerter.py --db /var/run/soc_station.db --webhook-url https://discord.com/api/webhooks/...
    
Severity threshold: Only alerts with severity <= 2 are notified (1=critical, 2=high)
"""

import sqlite3
import json
import argparse
import smtplib
import ssl
from datetime import datetime, timezone
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart


DB_PATH = '/app/db/soc_station.db'  # Default: Flask app database location


def get_unnotified_alerts(db_path, severity_threshold=2):
    """
    Query SQLite for un-notified alerts with acceptable severity.
    
    Args:
        db_path: Database path
        severity_threshold: Maximum severity to notify (1=critical, 2=high)
    
    Returns: list of alert records (sqlite3.Row)
    """
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    
    cursor.execute('''
        SELECT id, timestamp, src_ip, dest_ip, src_port, dest_port, 
               proto, signature, severity, category, raw_json
        FROM alerts
        WHERE notified = 0 AND severity <= ?
        ORDER BY severity ASC, timestamp DESC
        LIMIT 50  -- Batch process up to 50 alerts at once
    ''', (severity_threshold,))
    
    rows = cursor.fetchall()
    conn.close()
    
    return rows


def build_alert_message(alert_row):
    """Build formatted alert message for webhook/email."""
    severity_map = {
        '1': {'name': '🔴 CRITICAL', 'color': '#FF0000'},
        '2': {'name': '🟠 HIGH', 'color': '#FF9E64'},
        '3': {'name': '🟡 MEDIUM', 'color': '#FFC180'},
        '4': {'name': '🔵 LOW', 'color': '#73DACA'},
    }
    
    severity = alert_row['severity']
    sev_config = severity_map.get(severity, severity_map['4'])
    
    # Parse raw JSON if available
    try:
        raw_alert = json.loads(alert_row['raw_json']) if alert_row['raw_json'] else {}
    except (json.JSONDecodeError, TypeError):
        raw_alert = {}
    
    message = f"""
🚨 **SOC STATION ALERT** — {sev_config['name']}

---
**Signature:** `{alert_row['signature']}`

| Field | Value |
|-------|-------|
| Source IP | `{alert_row['src_ip']}` |
| Dest IP   | `{alert_row['dest_ip']}` |
| Protocol  | `{alert_row['proto']}` |
| Src Port  | {alert_row['src_port'] or 'N/A'} |
| Dst Port  | {alert_row['dest_port'] or 'N/A'} |
| Category  | `{alert_row['category'] or 'unknown'}` |
| Timestamp | `{alert_row['timestamp'][:19]}`Z |

---
*Auto-generated by SOC Station IDS pipeline*
"""
    
    # Add raw JSON to footer if available
    if alert_row['raw_json']:
        message += f"\n<details><summary>Raw JSON</summary>\n```json\n{alert_row['raw_json']}\n```\n</details>"
    
    return message


def send_discord_webhook(alert_row, webhook_url):
    """Send alert to Discord webhook."""
    if not webhook_url:
        return False
    
    payload = {
        'content': None,  # Use embed instead
        'username': 'SOC Station',
        'avatar_url': None,
        'embeds': [{
            'title': f'SOC STATION — 🚨 ALERT',
            'description': '',
            'color': severity_map.get(alert_row['severity'], {}).get('color', '#73DACA'),
            'fields': [
                {'name': 'Signature', 'value': alert_row['signature'], 'inline': True},
                {'name': 'Source', 'value': f"`{alert_row['src_ip']}:{alert_row['src_port'] or '-'} → {alert_row['dest_ip']}:{alert_row['dest_port'] or '-'}`", 'inline': True},
            ],
            'footer': {
                'text': 'SOC Station IDS Pipeline',
            },
            'timestamp': alert_row['timestamp'],
        }],
    }
    
    # Build embed fields properly (some need string conversion)
    sev_name = severity_map.get(alert_row['severity'], {}).get('name', 'LOW')
    payload['embeds'][0]['title'] = f'SOC STATION — {sev_name} ALERT'
    del payload['embeds'][0]['color']  # Remove placeholder
    
    try:
        import requests
        response = requests.post(webhook_url, json=payload, timeout=10)
        
        if response.status_code == 204:
            return True
        else:
            print(f'[-] Discord webhook failed (HTTP {response.status_code})')
            return False
            
    except Exception as e:
        print(f'[-] Discord webhook error: {e}')
        return False


def send_email_alert(alert_row, smtp_config):
    """Send alert via SMTP email."""
    if not smtp_config.get('enabled', False):
        return True  # Skip sending
    
    try:
        server = smtp_config['server']
        port = smtp_config.get('port', 587)
        username = smtp_config.get('username')
        password = smtp_config.get('password')
        
        msg = MIMEMultipart()
        msg['From'] = f'SOC Station <{username}>'.replace('<', '').replace('>', '')
        msg['To'] = 'soc-team@example.com'  # TODO: Configure recipients
        msg['Subject'] = f'[SOC STATION ALERT] — {severity_map.get(alert_row["severity"], {}).get("name", "UNKNOWN")}'
        
        body_text = build_alert_message(alert_row)
        body_html = (
            '<html>'
            '<head><style>'
            'body { font-family: sans-serif; padding: 20px; }'
            '.alert { border-left: 5px solid #FF0000; padding: 15px; margin: 10px 0; }'
            '</style></head>'
            '<body>'
            f'<h1>🚨 SOC STATION ALERT</h1>'
            f'<div class="alert"><strong>{severity_map.get(alert_row["severity"], {}).get("name", "UNKNOWN")}</strong><br>{alert_row["signature"]}</div>'
            f'<p>Source: <code>{alert_row["src_ip"]}:{alert_row["src_port"] or "-"}</code> → '
            f'Dest: <code>{alert_row["dest_ip"]}:{alert_row["dest_port"] or "-"}</code></p>'
            f'<p>Protocol: {alert_row["proto"]} | Category: {alert_row["category"] or "unknown"}</p>'
            '</body></html>'
        )
        
        msg.attach(MIMEText(body_text, 'plain'))
        msg.attach(MIMEText(body_html, 'html'))
        
        context = ssl.create_default_context()
        with smtplib.SMTP(server, port) as server:
            if username and password:
                server.login(username, password)
            # TODO: Add recipient list configuration
            
        return True
    except Exception as e:
        print(f'[-] Email alert failed: {e}')
        return False


def mark_alert_notified(db_path, alert_id):
    """Update alert status to notified=1 in database."""
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    
    cursor.execute('UPDATE alerts SET notified = 1 WHERE id = ?', (alert_id,))
    conn.commit()
    return cursor.rowcount


def main():
    parser = argparse.ArgumentParser(description='Alert Dispatcher for SOC Station')
    parser.add_argument('--db', default=DB_PATH, help='SQLite database path')
    parser.add_argument('--webhook-url', envvar='DISCORD_WEBHOOK_URL', help='Discord webhook URL (env or arg)')
    
    args = parser.parse_args()
    
    print(f'[*] Starting alert dispatcher...')
    print(f'[*] Database: {args.db}')
    print(f'[*] Discord Webhook: {"Configured" if args.webhook_url else "Not configured (Discord alerts disabled)"}')
    
    # Load SMTP config from settings.yaml (for email alerts)
    import yaml
    settings_path = '/app/config/settings.yaml'
    try:
        with open(settings_path, 'r') as f:
            settings = yaml.safe_load(f)[1]  # Skip YAML docstring comment
            smtp_config = settings.get('email', {}) or {}
    except Exception as e:
        print(f'[!] Could not load settings.yaml: {e}')
        smtp_config = {}
    
    while True:  # Continuous monitoring loop
        try:
            alerts = get_unnotified_alerts(args.db, severity_threshold=2)
            
            if alerts:
                print(f'\n[*] Found {len(alerts)} un-notified alert(s) — processing...')
                
                for alert in alerts:
                    success_webhook = False
                    success_email = False
                    
                    if args.webhook_url:
                        success_webhook = send_discord_webhook(alert, args.webhook_url)
                    
                    smtp_enabled = smtp_config.get('enabled', False) and smtp_config.get('server')
                    if smtp_enabled:
                        success_email = send_email_alert(alert, smtp_config)
                    
                    # Mark as notified if either method succeeded
                    if success_webhook or success_email:
                        rowcount = mark_alert_notified(args.db, alert['id'])
                        print(f'    [✓] Alert #{alert["id"]} marked as notified')
                    else:
                        print(f'    [-] Failed to send all notifications for Alert #{alert["id"]} — leaving un-notified')
            else:
                print('[i] No new alerts requiring notification')
            
            time.sleep(10)  # Poll every 10 seconds for new alerts
            
        except KeyboardInterrupt:
            print('\n[!] Stopping alert dispatcher...')
            break
        except Exception as e:
            print(f'[!] Error processing alerts: {e}')
            time.sleep(10)


if __name__ == '__main__':
    main()
